/**
 * Finding model + risk scoring for Repro-First Gate.
 */

/** @typedef {'critical'|'high'|'medium'|'low'} Severity */
/** @typedef {'proposed'|'ran-pass'|'ran-fail'|'skipped'} VerifyStatus */

/**
 * @typedef {object} Finding
 * @property {string} id
 * @property {string} title
 * @property {Severity} severity
 * @property {string} file
 * @property {number|null} line
 * @property {string} claim
 * @property {string} evidence
 * @property {string} verifyCommand
 * @property {string} [verifyCwdHint]
 * @property {VerifyStatus} status
 * @property {string} [skipReason]
 * @property {string} [runOutput]
 * @property {number|null} [exitCode]
 * @property {string|null} [suggestedPatch]
 * @property {string} [kind]
 */

const SEVERITY_WEIGHT = {
  critical: 40,
  high: 25,
  medium: 12,
  low: 5,
};

/**
 * @param {Finding[]} findings
 * @returns {{ score: number, label: 'LOW'|'MEDIUM'|'HIGH'|'CRITICAL', summary: string }}
 */
export function computeRisk(findings) {
  let score = 0;
  let verifiedFails = 0;
  let patches = 0;

  for (const f of findings) {
    let w = SEVERITY_WEIGHT[f.severity] ?? 5;
    if (f.status === "ran-fail") {
      w *= 1.5;
      verifiedFails += 1;
    } else if (f.status === "ran-pass") {
      w *= 0.35;
    } else if (f.status === "skipped") {
      w *= 0.8;
    }
    score += w;
    if (f.suggestedPatch) patches += 1;
  }

  score = Math.min(100, Math.round(score));
  let label = "LOW";
  if (score >= 70) label = "CRITICAL";
  else if (score >= 45) label = "HIGH";
  else if (score >= 20) label = "MEDIUM";

  const summary = `${verifiedFails} verified fail · ${patches} patch ready · risk: ${label}`;
  return { score, label, summary };
}

/**
 * @param {object} report
 * @returns {string}
 */
export function reportToMarkdown(report) {
  const lines = [];
  lines.push(`# PatchProof Report`);
  lines.push("");
  lines.push(`**Source:** ${report.sourceLabel}`);
  lines.push(`**Title:** ${report.title}`);
  lines.push(
    `**Risk:** ${report.risk.label} (${report.risk.score}/100) — ${report.risk.summary}`,
  );
  if (report.policy) {
    const p = report.policy;
    if (p.valid) {
      lines.push(`**Policy:** pass — no \`.patchproof.yml\` violations`);
    } else {
      lines.push(
        `**Policy:** FAIL — ${p.violations.length} \`.patchproof.yml\` violation(s)`,
      );
      for (const v of p.violations) {
        lines.push(`- ${v}`);
      }
    }
  }
  lines.push("");
  lines.push(`## Findings`);
  lines.push("");

  for (const f of report.findings) {
    lines.push(`### ${f.severity.toUpperCase()}: ${f.title}`);
    lines.push(`- **File:** \`${f.file}${f.line != null ? `:${f.line}` : ""}\``);
    lines.push(`- **Status:** \`${f.status}\``);
    lines.push(`- **Claim:** ${f.claim}`);
    lines.push(`- **Evidence:** ${f.evidence}`);
    lines.push(`- **Verify:** \`${f.verifyCommand}\``);
    if (f.skipReason) lines.push(`- **Skip reason:** ${f.skipReason}`);
    if (f.runOutput) {
      lines.push("");
      lines.push("```");
      lines.push(f.runOutput.trim().slice(0, 2000));
      lines.push("```");
    }
    if (f.suggestedPatch) {
      lines.push("");
      lines.push("**Suggested patch:**");
      lines.push("```diff");
      lines.push(f.suggestedPatch.trim());
      lines.push("```");
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "_Generated by PatchProof: Repro-First Gate — evidence over opinion._",
  );
  return lines.join("\n");
}

const SARIF_LEVEL = {
  critical: "error",
  high: "error",
  medium: "warning",
  low: "note",
};

/**
 * Convert report to SARIF 2.1.0 for GitHub Security tab.
 * @param {object} report
 * @returns {object}
 */
export function reportToSarif(report) {
  const rules = [];
  const results = [];
  const seenRules = new Set();

  for (const f of report.findings) {
    const ruleId = f.kind || f.id;
    if (!seenRules.has(ruleId)) {
      seenRules.add(ruleId);
      rules.push({
        id: ruleId,
        name: f.title,
        shortDescription: { text: f.title },
        fullDescription: { text: f.claim },
        defaultConfiguration: { level: SARIF_LEVEL[f.severity] ?? "note" },
      });
    }
    results.push({
      ruleId,
      level: SARIF_LEVEL[f.severity] ?? "note",
      message: {
        text: `${f.claim}\nStatus: ${f.status}\nEvidence: ${f.evidence}`,
      },
      locations: [
        {
          physicalLocation: {
            artifactLocation: { uri: f.file },
            ...(f.line != null
              ? { region: { startLine: f.line } }
              : {}),
          },
        },
      ],
      properties: {
        status: f.status,
        severity: f.severity,
        verified: f.status === "ran-fail" || f.status === "ran-pass",
      },
    });
  }

  return {
    $schema:
      "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
    version: "2.1.0",
    runs: [
      {
        tool: {
          driver: {
            name: "PatchProof",
            informationUri: "https://github.com/alfep/patchproof",
            version: "0.1.0",
            rules,
          },
        },
        results,
      },
    ],
  };
}
